import = [
  "~/.config/alacritty/dracula.toml"
]

[env]
TERM = "xterm-256color"

[font]
size = 14
normal = { family = "Hurmit Nerd Font Mono", style = "Regular" }

[window]
option_as_alt = "OnlyLeft"
