[[linux]]
names = []
to = '~/.config'

[[macOS]]
names = [ 'zsh', 'starship.toml', 'alacritty.toml', 'helix', 'templates' ]
to = '~/.config'

[[macOS]]
name = 'rc.zsh'
to = '~/'
rename = '.zshrc'

[[macOS]]
name = 'tmux.conf'
to = '~/'
rename = '.tmux.conf'

