[[linux]]
names = []
to = '~/.config'

[[macOS]]
names = [ 'lf', 'zsh', 'starship.toml' ]
to = '~/.config'

[[macOS]]
name = 'rc.zsh'
to = '~/.zshrc'

[[macOS]]
name = 'tmux.conf'
to = '~/.tmux.conf'

