[[linux]]
names = []
to = '~/.config'

[[macOS]]
names = [ 'zsh', 'starship.toml', 'ghostty', 'helix', 'templates' ]
to = '~/.config'

[[macOS]]
name = 'rc.zsh'
to = '~/'
rename = '.zshrc'

[[macOS]]
name = 'tmux.conf'
to = '~/'
rename = '.tmux.conf'

[[macOS]]
name = 'scripts'
to = '~/.local'

[[macOS]]
name = 'plot.gnu'
to = '~/'
rename = ".gnuplot"
