[global]
to = "~/.config"
exclude = [ ".git", "README.md", ".gitignore", "dotlink.toml" ]

[global.custom_links]
"tmux.conf" = "~/.tmux.conf"
"rc.zsh" = "~/.zshrc"
"rc.vrapper" = "~/.vrapperrc"

[presets.macOS]
exclude = [ "herbstluftwm", "mako", "i3", "picom.conf", "polybar", "sov", "sway", "waybar" ]

