#!/bin/bash

DOTDIR="$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"

checkDir() {
    if [[ ! -d $1 ]]; then
        echo "Folder $1 not found creating one..."
        mkdir -p $1
    fi
}

while read p; do
    if [[ x$p == x"-"* ]]; then
        FROM=$DOTDIR"/"$(echo $p | cut -d " " -f2) 
        TO=$(echo $p | cut -d " " -f5) 
        TO=${TO/\~/$HOME}
        DIR=$(echo $TO | rev | cut -d "/" -f2- | rev)
        
        checkDir $DIR
        ln -sf $FROM $TO
        echo "Linked $FROM to $TO"
    fi
done < $DOTDIR"/README.md"
